services:
  web-app:
    build: .
    ports:
    - "5000:5000"
    environment:
    - APP_USER=${USER_NAME}
    volumes:
    - ./logs:/app/logs # Bind Mount: memetakan folder lokal ke kontainer
    - shared-storage:/app/data
    networks:
    - mvc-network
  db-server:
    image: postgres:15-alpine
    environment:
    - POSTGRES_PASSWORD=rahasia
    volumes:
    - db-data:/var/lib/postgresql/data # Named Volume: untuk data DB
    networks:
    - mvc-network
volumes:
  db-data: # Definisi named volume global
  shared-storage:
networks:
  mvc-network:
    driver: bridge